GetApplicationTypesByLangcode:
   Masterdata_GetApplicationTypesByLangcode_allValid_smoke:
      endPoint: /v1/masterdata/applicationtypes/{langcode}
      role: admin
      restMethod: get
      inputTemplate: masterdata/GetApplicationTypesByLangcode/getApplicationTypesByLangcode
      outputTemplate: masterdata/GetApplicationTypesByLangcode/getApplicationTypesByLangcodeResult
      input: '{
   "langcode":"eng"
}'
      output: '{
   "response":{
      "applicationtypes":[
         {
            "langCode": "eng"
         }
      ]
   }
}'
   Masterdata_GetApplicationTypesByLangcode_InValid_langCode:
      endPoint: /v1/masterdata/applicationtypes/{langcode}
      role: admin
      restMethod: get
      inputTemplate: masterdata/GetApplicationTypesByLangcode/getApplicationTypesByLangcode
      outputTemplate: masterdata/error
      input: '{
   "langcode":"asdgav"
}'
      output: '{
   "errors": [
        {
            "errorCode": "KER-MSD-002",
            "message": "Application not found"
        }
    ]
}'