Configuration:
  status: warn
  name: Cucumber Logger

  Properties:
    Property:
      name: filename
      value: src/logs/mosip_qa.log

  Appenders:

    Console:
      name: Console_Appender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

    File:
      name: File_Appender
      append: false
      fileName: ${filename}
      PatternLayout:
        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"

#    RollingFile:
#      name: RollingFile_Appender
#      fileName: ${filename}
#      filePattern: "${filename}.%d{yyyy-MM-dd-hh-mm}.gz"
#      PatternLayout:
#        pattern: "[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n"
#      Policies:
#        SizeBasedTriggeringPolicy:
#          size: 100 KB
#      DefaultRollOverStrategy:
#        max: 0

  Loggers:

    Root:
      level: info
      AppenderRef:
        - ref: Console_Appender

    Logger:
      - name: mosip_qa
        level: info
        AppenderRef:
          - ref: File_Appender
            level: info
