apiVersion: v2
name: authdemo
description: A Helm chart to deploy authdemo for MOSIP modules
type: application
version: 12.1.0
appVersion: ""
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
home: https://mosip.io
keywords:
  - mosip
  - authdemo
maintainers:
  - email: info@mosip.io
    name: MOSIP
