modules:
  prereg:
    enabled: true
    image:
      repository: mosipid/apitest-prereg
      tag: 1.3.0-beta.1
      pullPolicy: Always
  masterdata:
    enabled: true
    image:
      repository: mosipid/apitest-masterdata
      tag: 1.3.0-beta.1
      pullPolicy: Always
  idrepo:
    enabled: true
    image:
      repository: mosipid/apitest-idrepo
      tag: 1.3.0-beta.1
      pullPolicy: Always
  partner:
    enabled: true
    image:
      repository: mosipid/apitest-pms
      tag: 1.2.2.2
      pullPolicy: Always
  pms:
    enabled: true
    image:
      repository: mosipid/apitest-pms
      tag: 1.2.2.2
      pullPolicy: Always
  resident:
    enabled: true
    image:
      repository: mosipid/apitest-resident
      tag: 1.3.0-beta.1
      pullPolicy: Always
  auth:
    enabled: true
    image:
      repository: mosipid/apitest-auth
      tag: 1.3.0-beta.1
      pullPolicy: Always
  esignet:
    enabled: true
    image:
      repository: mosipid/apitest-esignet
      tag: 1.6.2
      pullPolicy: Always
  mimoto:
    enabled: true
    image:
      repository: mosipid/apitest-mimoto
      tag: 0.19.2
      pullPolicy: Always
  injicertify:
    enabled: true
    image:
      repository: mosipid/apitest-injicertify
      tag: 0.13.0
      pullPolicy: Always
  injiverify:
    enabled: false
    image:
      repository: mosipid/apitest-inji-verify
      tag: 0.15.1
      pullPolicy: Always
  esignet-signup:
    enabled: true
    image:
      repository: mosipid/apitest-esignet-signup
      tag: 1.2.2
      pullPolicy: Always
  variables:
    push_reports_to_s3: "yes"
